{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"By using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkService"},{"type":"text","text":" you are able to start any network call"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/networkingframework"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/networkingframework"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This Framework is the Combine way of calling any API and recieving a generic responses."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"NetworkingFramework","title":"NetworkingFramework","symbolKind":"module","role":"collection","modules":[{"name":"NetworkingFramework"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkService","doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkError"]}],"references":{"doc://emadgnia.NetworkingFramework/documentation/NetworkingFramework/NetworkingFrameworkVersionNumber":{"role":"symbol","title":"NetworkingFrameworkVersionNumber","fragments":[{"kind":"identifier","text":"NetworkingFrameworkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for NetworkingFramework."}],"identifier":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkingFrameworkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/networkingframework\/networkingframeworkversionnumber"},"doc://emadgnia.NetworkingFramework/documentation/NetworkingFramework/NetworkService":{"role":"symbol","title":"NetworkService","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkService"}],"abstract":[{"type":"text","text":"Netwroking Service"}],"identifier":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkService"}],"url":"\/documentation\/networkingframework\/networkservice"},"doc://emadgnia.NetworkingFramework/documentation/NetworkingFramework":{"role":"collection","title":"NetworkingFramework","abstract":[{"type":"text","text":"This Framework is the Combine way of calling any API and recieving a generic responses."}],"identifier":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework","kind":"symbol","type":"topic","url":"\/documentation\/networkingframework"},"doc://emadgnia.NetworkingFramework/documentation/NetworkingFramework/NetworkError":{"role":"symbol","title":"NetworkError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkError"}],"abstract":[{"type":"text","text":"Defines the Network service errors."}],"identifier":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkError"}],"url":"\/documentation\/networkingframework\/networkerror"},"doc://emadgnia.NetworkingFramework/documentation/NetworkingFramework/NetworkingFrameworkVersionString":{"role":"symbol","title":"NetworkingFrameworkVersionString","fragments":[{"kind":"identifier","text":"NetworkingFrameworkVersionString"}],"abstract":[{"type":"text","text":"Project version string for NetworkingFramework."}],"identifier":"doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkingFrameworkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/networkingframework\/networkingframeworkversionstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkingFrameworkVersionNumber","doc:\/\/emadgnia.NetworkingFramework\/documentation\/NetworkingFramework\/NetworkingFrameworkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}